Qa::Authorities::Local.register_subauthority('tgn', 'TGN')
Qa::Authorities::Local.register_subauthority('tgnuk', 'TgnUk')
Qa::Authorities::Local.register_subauthority('terms', 'Terms')

Qa::Authorities::Local.register_subauthority('folio_faces', 'FolioFaceTerms')
Qa::Authorities::Local.register_subauthority('folio_types', 'FolioTerms')
Qa::Authorities::Local.register_subauthority('currencies', 'CurrencyTerms')
Qa::Authorities::Local.register_subauthority('person_roles', 'PersonRoleTerms')
Qa::Authorities::Local.register_subauthority('statuses', 'StatusTerms')
Qa::Authorities::Local.register_subauthority('place_types', 'PlaceTypeTerms')
Qa::Authorities::Local.register_subauthority('certainty', 'CertaintyTerms')
Qa::Authorities::Local.register_subauthority('languages', 'LanguageTerms')
Qa::Authorities::Local.register_subauthority('single_dates', 'SingleDateTerms')
Qa::Authorities::Local.register_subauthority('place_roles', 'PlaceRoleTerms')
Qa::Authorities::Local.register_subauthority('date_roles', 'DateRoleTerms')
Qa::Authorities::Local.register_subauthority('entry_types', 'EntryTypeTerms')
