Qa::Authorities::Local.register_subauthority('tgn', 'TGN')
Qa::Authorities::Local.register_subauthority('tgnuk', 'TgnUk')
Qa::Authorities::Local.register_subauthority('terms', 'Terms')

Qa::Authorities::Local.register_subauthority('folio-faces', 'FolioFaceTerms')
Qa::Authorities::Local.register_subauthority('folios', 'FolioTerms')
Qa::Authorities::Local.register_subauthority('currencies', 'CurrencyTerms')

Qa::Authorities::Local.register_subauthority('roles', 'RoleTerms')
Qa::Authorities::Local.register_subauthority('qualifications', 'QualTerms')
Qa::Authorities::Local.register_subauthority('statuses', 'StatusTerms')
Qa::Authorities::Local.register_subauthority('place-types', 'PlaceTypeTerms')
Qa::Authorities::Local.register_subauthority('date-types', 'DateTypeTerms')
Qa::Authorities::Local.register_subauthority('certainty', 'CertaintyTerms')
Qa::Authorities::Local.register_subauthority('languages', 'LanguageTerms')
Qa::Authorities::Local.register_subauthority('formats', 'FormatTerms')
Qa::Authorities::Local.register_subauthority('singledates', 'SingleDateTerms')
