include Terms
Qa::Authorities::Local.register_subauthority('deep', 'Deep')
Qa::Authorities::Local.register_subauthority('unlock', 'Unlock')
Qa::Authorities::Local.register_subauthority('tgnuk', 'TgnUk')
Qa::Authorities::Local.register_subauthority('folio_faces', 'FolioFaceTerms')
Qa::Authorities::Local.register_subauthority('folio_types', 'FolioTerms')
#Qa::Authorities::Local.register_subauthority('currencies', 'CurrencyTerms') # not using
Qa::Authorities::Local.register_subauthority('person_roles', 'PersonRoleTerms')
Qa::Authorities::Local.register_subauthority('descriptors', 'DescriptorTerms')
Qa::Authorities::Local.register_subauthority('place_types', 'PlaceTypeTerms')
Qa::Authorities::Local.register_subauthority('date_types', 'DateTypeTerms')
Qa::Authorities::Local.register_subauthority('certainty', 'CertaintyTerms')
Qa::Authorities::Local.register_subauthority('languages', 'LanguageTerms')
Qa::Authorities::Local.register_subauthority('formats', 'FormatTerms')
# Qa::Authorities::Local.register_subauthority('single_dates', 'SingleDateTerms')
Qa::Authorities::Local.register_subauthority('place_roles', 'PlaceRoleTerms')
Qa::Authorities::Local.register_subauthority('date_roles', 'DateRoleTerms')
Qa::Authorities::Local.register_subauthority('persons', 'PersonTerms')
Qa::Authorities::Local.register_subauthority('places', 'PlaceTerms')
Qa::Authorities::Local.register_subauthority('entry_types', 'EntryTypeTerms')
