:terms:
    - :id: http://lexvo.org/id/script/Latn
      :term: Latin
    - :id: http://lexvo.org/id/term/eng/English
      :term: English
    - :id: http://lexvo.org/id/term/eng/French
      :term: French